import { Tag } from '@core/models/tag.model';

export const TAGS: Tag[] = [
  { name: 'dart' },
  { name: 'flutter' },
  { name: 'firebase' },
  { name: 'react' },
  { name: 'react-native' },
  { name: 'd3' },
  { name: 'javascript' },
  { name: 'animation' },
  { name: 'git' },
  { name: 'github' },
  { name: 'firestore' },
  { name: 'next' },
  { name: 'go' },
  { name: 'css' },
  { name: 'svg' },
  { name: 'hooks' },
  { name: 'cloud-functions' },
  { name: 'pri' },
  { name: 'payments' },
  { name: 'fauna' },
  { name: 'docker' },
  { name: 'node' },
  { name: 'typescript' },
  { name: 'stripe' },
  { name: 'vue' },
  { name: 'graphql' },
  { name: 'electron' },
  { name: 'svelte' },
  { name: 'ios' },
  { name: 'angular' },
  { name: 'minimum-viable-product' },
  { name: 'nest' },
  { name: 'android' },
  { name: 'ionic' },
  { name: 'rxjs' },
  { name: 'python' },
  { name: 'machine-learning' },
  { name: 'nosql' },
  { name: 'jest' },
  { name: 'auth' },
];
